### ISSUE TITLE
postInstall: typings install

### ISSUE THREAD

**Issue by bergben** [vinaygopinath/ng2-meta#10]
Hey there!

The script "postinstall": "typings install" creates some trouble when deploying to [Heroku](http://www.heroku.com). 
Why do you need the typings install as a postInstall script? I have created a pull request here to change that... #9. This pull would fix this issue.

The problem is that on Heroku all npm packages are installed from a start so typings isn't installed at the moment when ng2-meta gets installed -> therefore an error is thrown and the application can't be deployed.

**Comment by vinaygopinath** [comment]
Hi,

Thanks for your contribution. Running `typings install` provides type definitions for ng2-meta's internal dependencies (like Jasmine). The installed type definitions are useful only for those contributing code to ng2-meta - admittedly, a small set of people :)

The switch to prepublish is clever, as, according to the [npm docs](https://docs.npmjs.com/misc/scripts), it would be executed when the package is published _and_ when this repo is cloned and `npm install` is called, something that a contributor is likely to do.
