### ISSUE TITLE
No exported member 'ActivateRoute'. Does this works with RC4?

### ISSUE THREAD

**Issue by UooVeee** [vinaygopinath/ng2-meta#2]
**websitefrontend/node_modules/ng2-meta/dist/meta.service.d.ts:2:18 
    Module 
websitefrontend/node_modules/@angular/router/index"' has no exported member 'ActivatedRoute'.**

**Comment by vinaygopinath** [comment]
Hi,

RC4 is supported. Can you please make sure you're using the right version (the version of @angular/router specified in your app's `package.json`, node_modules/@angular/router/package.json, npm update, etc)?

**Comment by bergben** [comment]
Hey @UooVeee, I have just tested this with RC4 and wasn't able to reproduce your issue. So it should indeed be a matter of configuration as @vinaygopinath suggests...
