### ISSUE TITLE
ng2-meta issue in systemjs

### ISSUE THREAD

**Issue by ghost** [vinaygopinath/ng2-meta#21]
I setup component as per your instruction, but could not get it work. I am using SystemJS, error below:

Unhandled Promise rejection:

(SystemJS) expected expression, got '<'
	@http://localhost:3000/app.module.js:22:18
	@http://localhost:3000/app.module.js:1:31
	@http://localhost:3000/app.module.js:1:2
	@http://localhost:3000/index.js:3:20
	@http://localhost:3000/index.js:1:31
	@http://localhost:3000/index.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:232:17
	Zone.prototype.run@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:114:24
	scheduleResolveOrReject/<@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:502:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:265:21
	Zone.prototype.runTask@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:154:28
	drainMicroTaskQueue@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:401:25
	ZoneTask/this.invoke@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:339:25
	
	Evaluating http://localhost:3000/ng2-meta.js
	Evaluating http://localhost:3000/app.module.js
	Evaluating http://localhost:3000/index.js
	Error loading http://localhost:3000/index.js

; Zone: <root> ; Task: Promise.then ; Value:
Error: (SystemJS) expected expression, got '<' @http://localhost:3000/app.module.js:22:18 @http://localhost:3000/app.module.js:1:31 @http://localhost:3000/app.module.js:1:2 @http://localhost:3000/index.js:3:20 @http://localhost:3000/index.js:1:31 @http://localhost:3000/index.js:1:2 ZoneDelegate.prototype.invoke@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:232:17 Zone.prototype.run@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:114:24 scheduleResolveOrReject/<@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:502:52 ZoneDelegate.prototype.invokeTask@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:265:21 Zone.prototype.runTask@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:154:28 drainMicroTaskQueue@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:401:25 ZoneTask/this.invoke@http://localhost:3000/zone.js/dist/zone.js?rev=@@hash:339:25 Evaluating http://localhost:3000/ng2-meta.js Evaluating http://localhost:3000/app.module.js Evaluating http://localhost:3000/index.js Error loading http://localhost:3000/index.js

My App.Module.ts file is:

import { NgModule }               from '@angular/core';
import { HttpModule }             from '@angular/http';
import { FormsModule, 
          FormBuilder }           from '@angular/forms';
import { BrowserModule  }         from '@angular/platform-browser';
import { AppComponent }           from './app.component';
import { LayoutModule }           from './layout/layout.module';

import { HeaderComponent }        from './layout/components/header';
import { PrivateHeaderComponent } from './layout/components/privateheader';
import { HomeBannerComponent }    from './layout/components/homebanner';
import { FooterComponent }        from './layout/components/footer';

import { routing, 
          appRoutingProviders }   from './app.routing';
import { MetaModule } from 'ng2-meta';

import { SharedModule }           from './shared/shared.module';
import { sharedrouting }          from './shared/shared.routing';

import { AppService }             from './app.service';

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    LayoutModule,
    SharedModule,
    sharedrouting,  
    routing,
    MetaModule.forRoot()
  ],
  declarations: [
    AppComponent,
    HeaderComponent,
    PrivateHeaderComponent,
    HomeBannerComponent,    
    FooterComponent    
  ],
  providers: [
    appRoutingProviders,
    AppService
  ],
  bootstrap: [
    AppComponent
  ],
})
export class AppModule { }

**Comment by uiktiomasfeliz** [comment]
Hy @jariwbh you need to add into system.config.js
`map: {
'ng2-meta': 'npm:ng2-meta'
}`

and

`packages: {
'ng2-meta': {
        main: 'dist/index.js',
        defaultExtension: 'js'
      }
 }`
