### ISSUE TITLE
Cannot read property 'firstChild' of null

### ISSUE THREAD

**Issue by Iraecio** [vinaygopinath/ng2-meta#26]
when inject MetaService in component, has a TypeError: Cannot read property 'firstChild' of null;
`
ActivatedRouteSnapshot 
....
firstChild:null
....
`

**Comment by modernfidelity** [comment]
Any luck resolving this one ?

**Comment by sachingk** [comment]
Even I am also getting the same error. What is the reason for this error ?

**Comment by RathodGirish** [comment]
I am also getting same issue. Any solution please.

**Comment by vinaygopinath** [comment]
This issue is no longer relevant as the code that referred to `firstChild` has been refactored as of v4.0.0.
