### ISSUE TITLE
error with new Angular 4.0.0

### ISSUE THREAD

**Issue by itswadesh** [vinaygopinath/ng2-meta#35]
Error: ```ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/shopnx/src/app/app.module.ts, resolving symbol AppModule in D:/shopnx/src/app/app.module.ts```

Env:
----------------
angular-cli 1.0.0
angular 4.0.0

When I do ```ng serve``` The above error comes. Although it still allows me to run the application, but it does not allow me to create a production build.

**Comment by JoshuaNovak919** [comment]
Anyone figure out a workaround for this?

**Comment by eventengine** [comment]
@JoshuaNovak919 +10000000000000

**Comment by souuu** [comment]
Is there a solution for this ?

**Comment by codingwithrachel** [comment]
Angular4 offers meta service for metatags http://blog.ninja-squad.com/2017/03/24/what-is-new-angular-4/
Ended up switching over this ^
