### ISSUE TITLE
Can i set the metadata tags dynamically ?

### ISSUE THREAD

**Issue by gomesNazareth** [vinaygopinath/ng2-meta#38]
I am getting the meta data tags for the pages from an API. Is there a way to set this dynamic meta data in the routes. Like the sample code below . Is is possible?

```
export const PublicPageRoutes: Array<any> = [
  { path: '', component: Home2Component, canActivate: [CanHomeActivateGuard], data: {
      meta: {
         title: AccountService.seoList['home']['page_title'],
        description:  AccountService.seoList['home']['description']
  }
}
,},
```

**Comment by simonKristensen** [comment]
Commenting to ask the same. I need to know if it is possible to set them asynchronously with Observables or Promises

**Comment by vinaygopinath** [comment]
Sorry for the (very) late reply, but this is supported (and mentioned in the README).

Just inject `MetaService` into your component and use the `setTitle` or `setTag` methods.

Note that server-side rendering may complete before your observable completes successfully, so you might want to use a Angular route [Resolve](https://angular.io/api/router/Resolve) to ensure that the tags are set ([Example](https://github.com/vinaygopinath/NomadCouple/blob/master/src/app/search/visa-data.resolver.ts#L22))

```typescript
this.http.get(SOME_URL)
  .subscribe((data: SomeResponse) => {
    this.metaService.setTitle('Title of the page ' + data.title);
    this.metaService.setTag('description', data.description);
  });
```
