### ISSUE TITLE
meta name => meta property

### ISSUE THREAD

**Issue by MurhafSousli** [vinaygopinath/ng2-meta#4]
Hi, there is an issue getting meta tags to work in facebook, I tried the debugger and found out only the title is changing, I think you should update the code `meta[name]` to `meta[property]`

```
 private _getOrCreateMetaTag(name: string): HTMLElement {
    let el: HTMLElement = this.document.querySelector('meta[property=\'' + name + '\']');
    .
    .
}
```

check this http://stackoverflow.com/questions/9953779/get-wrong-ogtype-in-object-debugger

**Comment by vinaygopinath** [comment]
The Open Graph protocol uses the `property` attribute that is defined in the RDFa spec, not the HTML5 spec. Making `property` the default attribute, even for non-OG meta tags, would show errors in HTML validators if the doctype does not include RDFa. References: [1](https://groups.google.com/forum/#!topic/open-graph-protocol/b7gnaMnW9XU) [2](https://www.w3.org/TR/html5/document-metadata.html#the-meta-element) [3](http://stackoverflow.com/questions/22350105/whats-the-difference-between-meta-name-and-meta-property)

Also, it looks like Facebook picks up the meta name values, showing only a warning that the `meta property` tag must be explicitly defined. For example, here's my site [Nomad Couple on Facebook sharing debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fvinaygopinath.github.io%2FNomadCouple%2Fstart) - It shows the right title, description and share image even though the site uses `<meta name="xx" content="yy">` for all meta tags. Can you share your site URL?

**Comment by MurhafSousli** [comment]
Cool, so it's just a warning, because I read couple of answers about OG on stackoverflow, they are saying replace them, I haven't got any errors, however I couldn't modify your service and use it internally, (it throws no provider exception and only accepting the provider when I import it from NPM) 

I liked this [answer](http://stackoverflow.com/questions/20401085/is-it-possible-to-use-the-same-meta-tag-for-opengraph-and-schema-org/20429551#20429551), when he uses both name and property in the meta tag `<meta name="description" property="og:description" content="great description" />` (sounds convience)

here are some links: 
http://murhafsousli.com/posts/127
http://murhafsousli.com/posts/128
http://murhafsousli.com/about

all requests in the debugger is returning 404 in respose code, except my base url http://murhafsousli.com/

_I have set a default title, description and image, so probably everything will look fine, but actually only the title is working when the post open, they will change to match the post meta._
