### ISSUE TITLE
Does this work in RC5?

### ISSUE THREAD

**Issue by bencameron00** [vinaygopinath/ng2-meta#5]
Hi

I have been using ng2-meta with RC4 and below. I have now updated my app to use RC5 and am no longer seeing the meta tags come through.

Does ng2-meta support RC5?

**Comment by martinop** [comment]
SetTitle programmatically doesnt work

**Comment by NathanLawrence** [comment]
RC4 also deprecates the provide() method, making the bootstrap process very confusing. Thoughts on fixing this?

**Comment by bencameron00** [comment]
Ng 2.0 Final is now out.
