### ISSUE TITLE
SetTitle programmatically

### ISSUE THREAD

**Issue by martinop** [vinaygopinath/ng2-meta#7]
Why this doesnt work? Just the tags works. rc5

**Comment by bergben** [comment]
Hey @martinop . 
Can you elaborate on what exaclty isn't working? 

To set the document title in the component you can just use the Angular Title service:
https://angular.io/docs/ts/latest/cookbook/set-document-title.html

**Comment by vinaygopinath** [comment]
@martinop I've just published v2.0.0 on npm. Can you use that version and report back here if you're still running into issues with `setTitle`? Thanks.

**Comment by rybaczewa** [comment]
I have the same problem with v2.0.1 (installed from github due to https://github.com/vinaygopinath/ng2-meta/issues/13). I am using angular2 and ng2-meta with webpack.

Using setTitle in AppComponent works but is instantly overriten by either title from route meta or default title from MetaConfig (depending on whether meta title is provided for route).

```
export class AppComponent {
  constructor(private metaService: MetaService) {
    // This works but is instantly overriten
    this.metaService.setTitle('test');
  }
}
```

Using setTitle on other any of route components does nothing. Using setTag is fine.

```
export class ObjDetailComponent implements OnInit {
  constructor(
    private metaService: MetaService
  ) {}

  ngOnInit(): void {
    // this changes nothing
    this.metaService.setTitle('test');

    // this works as intended
    this.metaService.setTag('og:image', '...');
  }
}
```

**Comment by vinaygopinath** [comment]
Hey @rybaczewa, I'm aware of this possibility. A component's constructor is called (and `metaService.setTitle` within it) before the "route change completed" router event (when the route meta and/or default values are used for the title/other meta tags).

I intended for `setTitle` to be used in an asynchronous way, possibly after an HTTP request (as in [here](https://github.com/vinaygopinath/NomadCouple/blob/master/src/app/search/search.component.ts#L46)). I didn't consider that `setTitle` could be used in conjunction with route meta/defaults. To set the title (and other tags that might be in collision with route meta/defaults) programmatically _after_ the route change completed event, use `setTimeout`

``` javascript
setTimeout(() => {
  this.metaService.setTitle('test');
});
```

Meanwhile, I'll look into making sure that programmatic changes have precedence over route meta and default values.

**Comment by rybaczewa** [comment]
Oh, I see. I assumed that setTitle at respects MetaConfig defaults, especially title suffix (so there's no need for suffix to be set every time I use setTitle). Thanks for the info though.

**Comment by shabbir-dhangot** [comment]
@vinaygopinath  Is it ok to use in setTimeout(). Is it a proper way for SEO ?
